/* eslint-disable no-unused-vars */
const playersData = [
    { "name": "A Sqrd", "amount": 10 },
    { "name": "Abrafebre", "amount": 10 },
    { "name": "AbusiveTunaa", "amount": 10 },
    { "name": "a sync", "amount": 35 },
    { "name": "ags friend", "amount": 10 },
    { "name": "bongij_mi", "amount": 10 },
    { "name": "Combatt1ron", "amount": 10 },
    { "name": "Cuhmmies", "amount": 11 },
    { "name": "Connorz", "amount": 20 },
    { "name": "Desports Btw", "amount": 10 },
    { "name": "Don Corgione", "amount": 10 },
    { "name": "dj i nn", "amount": 33 },
    { "name": "F aladorable", "amount": 60 },
    { "name": "Fe brimstone", "amount": 10 },
    { "name": "F loofy", "amount": 10 },
    { "name": "Frelya", "amount": 10 },
    { "name": "kazpu", "amount": 10 },
    { "name": "Kundaii", "amount": 10 },
    { "name": "Goose L", "amount": 111 },
    { "name": "Goose World", "amount": 112 },
    { "name": "High Bonsai", "amount": 10 },
    { "name": "Imago Loop", "amount": 10 },
    { "name": "IM Ivar", "amount": 10 },
    { "name": "Iron Chkn", "amount": 10 },
    { "name": "Ironcg", "amount": 20 },
    { "name": "J mes", "amount": 10 },
    { "name": "Joan Of Arf", "amount": 10 },
    { "name": "Justen", "amount": 10 },
    { "name": "Lord Oziach", "amount": 0 },
    { "name": "MilkMate", "amount": 0 },
    { "name": "MXIIA", "amount": 10 },
    { "name": "Nerding Out", "amount": 10 },
    { "name": "Noble Mobile", "amount": 40 },
    { "name": "I got no Job", "amount": 10 },
    { "name": "I Run East", "amount": 10 },
    { "name": "Ninef", "amount": 30 },
    { "name": "P Dirty soda", "amount": 10 },
    { "name": "Sailor Terry", "amount": 10 },
    { "name": "Sacred Clays", "amount": 10 },
    { "name": "Shaharrav", "amount": 10 },
    { "name": "Slaymebb", "amount": 47 },
    { "name": "Sticky Died", "amount": 10 },
    { "name": "Tiiiiiiiiiim", "amount": 28 },
    { "name": "Vyraal1", "amount": 10 },
    { "name": "Vorkathchan", "amount": 10 },
    { "name": "Zero Rangers", "amount": 10 }    
];

export default playersData;
