/* eslint-disable no-unused-vars */
const playersData = [
    { "name": "A Sqrd", "amount": 0 },
    { "name": "Abrafebre", "amount": 10 },
    { "name": "AbusiveTunaa", "amount": 10 },
    { "name": "a sync", "amount": 10 },
    { "name": "chungy", "amount": 0 },
    { "name": "Connorz", "amount": 10 },
    { "name": "Desports Btw", "amount": 0 },
    { "name": "dj i nn", "amount": 0 },
    { "name": "Floofy", "amount": 10 },
    { "name": "Goose L", "amount": 30 },
    { "name": "Goose World", "amount": 10 },
    { "name": "High Bonsai", "amount": 0 },
    { "name": "Imago Loop", "amount": 10 },
    { "name": "Iron Chkn", "amount": 0 },
    { "name": "Ironcg", "amount": 0 },
    { "name": "J mes", "amount": 0 },
    { "name": "Joan Of Arf", "amount": 10 },
    { "name": "Justen", "amount": 0 },
    { "name": "Lord Oziach", "amount": 0 },
    { "name": "MilkMate", "amount": 0 },
    { "name": "MXIIA", "amount": 10 },
    { "name": "Mrkvic", "amount": 0 },
    { "name": "Noble Mobile", "amount": 0 },
    { "name": "NoJobperson", "amount": 10 },
    { "name": "Ninef", "amount": 0 },
    { "name": "Sailor Terry", "amount": 0 },
    { "name": "Shaharrav", "amount": 10 },
    { "name": "Slaymebb", "amount": 37 },
    { "name": "snp500", "amount": 0 },
    { "name": "Tiiiiiiiiiim", "amount": 28 },
    { "name": "Zero Rangers", "amount": 10 }    
];

export default playersData;
