name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.EC2_IP}}
        username: ubuntu
        key: ${{secrets.EC2_SSH_KEY}}
        script: |
          git pull origin main
          npm install
          npm restart
